"""Three-way validation: forecast (cell) vs gridded analysis (cell) vs gauges.

The gridded series every score in this project is computed against is worse than
a suspect judge -- it is a relative of one of the defendants. Open-Meteo's
archive `best_match` serves ECMWF IFS HRES at 9 km for 2026, so verifying
`ecmwf_ifs025` against it is close to asking ECMWF to mark its own work. (Older
versions of this pipeline called that series ERA5, which understated the
problem: ERA5 is at least a reanalysis, and it is now carried separately as a
third arbiter.) On top of that, neither product assimilates Chilean rain gauges
-- their precipitation is generated by the forecast model inside the
assimilation -- and both are cell averages being compared with a city.

Rain gauges are the only arbiter here not made by a model, and this script uses
them three ways:

  A3  Event totals per city, gauges vs gridded vs each model, over the core of
      the event and over the full episode -- always on days the gauges actually
      reported, with the gridded series and the forecasts masked to those days.
  A4  Daily comparison: series per city, the gridded-vs-gauge scatter that
      quantifies the representativeness gap, and a sensitivity test that
      recomputes the headline scores with the gauges as truth.

The gap between a cell and a gauge is not a measure of who is lying. A cell
average and a point measurement are different quantities, and the difference
between them is the thing being measured here.

A city's rainfall is estimated from *all* of its gauges rather than the nearest
one, because the choice of point moves the answer: at La Serena the nearest
gauge is also the lowest of the six inside that cell, and picking it turns a
+72% gap into a +122% one. The estimator and its QC live in stations_common.py
so that verify.py and coverage_analysis.py score against exactly the same
numbers.

Outputs CSVs to data/processed/<capture>/metrics/ and two PNGs to figures/.

Usage: uv run scripts/station_validation.py [--capture YYYY-MM-DD]
"""

import argparse
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from coverage_analysis import spearman  # noqa: E402
from stations_common import (  # noqa: E402
    city_gauge_daily,
    event_window,
    gauge_quality,
    load_gauges,
)
from verify import (  # noqa: E402
    AXIS,
    CITY_LABELS,
    CITY_ORDER,
    ENSEMBLE_MEMBERS,
    INK,
    MODEL_COLORS,
    set_style,
)

ROOT = Path(__file__).resolve().parent.parent

STATION_COLOR = "#0d366b"
# The gauge bar in fig6 carries the individual gauges as open circles on top,
# so it is drawn in a light neutral rather than the navy used for the markers.
STATION_BAR_COLOR = "#c8c4b9"
GRID_COLOR = "#6da7ec"


def load(capture: str) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame,
                                pd.DataFrame]:
    proc = ROOT / "data" / "processed" / capture
    tidy = pd.read_parquet(proc / "tidy_daily.parquet")
    gauges = load_gauges(capture)
    quality = gauge_quality(gauges)
    city = city_gauge_daily(gauges, quality)
    return tidy, gauges, quality, city


def in_window(dates: pd.Series, window: tuple[str, str]) -> pd.Series:
    return dates.astype(str).between(*window)


# ----------------------------------------------------- A3 event totals

def event_totals(tidy: pd.DataFrame, city_est: pd.DataFrame,
                 window: tuple[str, str], leads=(1, 5)) -> pd.DataFrame:
    """Gauge / gridded / forecast totals per city, paired on the gauge's days.

    A city whose gauges missed a day would otherwise be compared against a
    gridded total that includes it; every series here is summed over exactly
    the same dates.
    """
    grid = tidy[["city", "valid_date", "precip_grid_mm"]].drop_duplicates()
    era5 = tidy[["city", "valid_date", "precip_era5_mm"]].drop_duplicates()
    rows = []
    p = city_est[in_window(city_est["valid_date"], window)]
    for city, g in p.groupby("city"):
        days = set(g["valid_date"])
        e = grid[(grid["city"] == city) & (grid["valid_date"].isin(days))]
        e5 = era5[(era5["city"] == city) & (era5["valid_date"].isin(days))]
        row = {
            "window": f"{window[0]}..{window[1]}", "city": city,
            "n_days": len(days),
            "station_mm": g["precip_gauge_mm"].sum(),
            "n_gauges": int(g["n_gauges"].max()),
            "grid_mm": e["precip_grid_mm"].sum(),
            "era5_mm": e5["precip_era5_mm"].sum(),
        }
        f = tidy[(tidy["city"] == city) & (tidy["valid_date"].isin(days))]
        for model, gm in f.groupby("model"):
            for lead in leads:
                sel = gm[gm["lead_days"] == lead]
                row[f"{model}_lead{lead}_mm"] = (
                    sel["precip_fcst_mm"].sum() if len(sel) == len(days)
                    else np.nan)
        for tag in ("grid", "era5"):
            row[f"{tag}_over_station"] = (row[f"{tag}_mm"] / row["station_mm"]
                                          if row["station_mm"] > 0 else np.nan)
        rows.append(row)
    return pd.DataFrame(rows)


# ------------------------------------------------- A4 daily comparison

def daily_station_vs_grid(tidy: pd.DataFrame,
                          city_est: pd.DataFrame) -> tuple[pd.DataFrame,
                                                           pd.DataFrame]:
    """Paired daily gauge/gridded table, with correlation and bias statistics.

    The correlation is also reported on the square root of both series: daily
    precipitation is strongly right-skewed, and on the raw scale a handful of
    storm days would set r almost by themselves.
    """
    gridded = tidy[["city", "valid_date", "precip_grid_mm",
                    "precip_era5_mm"]].drop_duplicates()
    paired = city_est.merge(gridded, on=["city", "valid_date"])

    rows = []
    for tag in ("grid", "era5"):
        col = f"precip_{tag}_mm"
        base = paired.dropna(subset=[col])
        for city, gc in [("(pooled)", base)] + list(base.groupby("city")):
            s, e = gc["precip_gauge_mm"], gc[col]
            if len(gc) < 3:
                continue
            rows.append({
                "gridded": tag, "city": city, "n": len(gc),
                "n_gauges": int(gc["n_gauges"].max()),
                "station_mean_mm": s.mean(), "gridded_mean_mm": e.mean(),
                "bias_mm": (e - s).mean(),
                "bias_pc": 100 * (e.sum() / s.sum() - 1) if s.sum() > 0 else np.nan,
                "mae_mm": (e - s).abs().mean(),
                "pearson_r": s.corr(e),
                "pearson_r_sqrt": np.sqrt(s).corr(np.sqrt(e)),
                "spearman": spearman(s, e),
            })
    return paired, pd.DataFrame(rows)


def sensitivity(tidy: pd.DataFrame, paired: pd.DataFrame,
                thr: float = 10.0) -> pd.DataFrame:
    """Headline scores under each arbiter, over exactly the same city-days.

    Restricting all three to the city-days the gauges cover is what makes the
    comparison about the arbiter rather than about the sample. robustness.py
    then asks whether the gaps found here are larger than sampling noise.
    """
    rows = []
    for subset in ("gauge-covered city-days",):
        keys = paired[["city", "valid_date", "precip_gauge_mm"]]
        df = tidy.merge(keys, on=["city", "valid_date"], how="inner")
        for truth_name, truth_col in [("gauge", "precip_gauge_mm"),
                                      ("grid", "precip_grid_mm"),
                                      ("era5", "precip_era5_mm")]:
            y = df[truth_col]
            err = df["precip_fcst_mm"] - y
            hit = (df["precip_fcst_mm"] >= thr) & (y >= thr)
            miss = (df["precip_fcst_mm"] < thr) & (y >= thr)
            fa = (df["precip_fcst_mm"] >= thr) & (y < thr)
            work = df.assign(err=err, hit=hit, miss=miss, fa=fa)
            for (model, lead), g in work.groupby(["model", "lead_days"]):
                h, m_, f_ = g["hit"].sum(), g["miss"].sum(), g["fa"].sum()
                rows.append({
                    "subset": subset, "truth": truth_name, "model": model,
                    "lead_days": lead, "n": len(g),
                    "mae_mm": g["err"].abs().mean(),
                    "bias_mm": g["err"].mean(),
                    "pod": h / (h + m_) if h + m_ else np.nan,
                    "far": f_ / (h + f_) if h + f_ else np.nan,
                })
            # Poor man's ensemble Brier skill score against the same truth.
            wide = (work[work["model"].isin(ENSEMBLE_MEMBERS)]
                    .pivot_table(index=["city", "valid_date", "lead_days", truth_col],
                                 columns="model", values="precip_fcst_mm")
                    .dropna().reset_index())
            prob = (wide[ENSEMBLE_MEMBERS] >= thr).mean(axis=1)
            event = (wide[truth_col] >= thr).astype(float)
            for lead, g in pd.DataFrame({"lead_days": wide["lead_days"],
                                         "prob": prob, "event": event}
                                        ).groupby("lead_days"):
                base = g["event"].mean()
                bs = ((g["prob"] - g["event"]) ** 2).mean()
                rows.append({
                    "subset": subset, "truth": truth_name, "model": "ensemble3",
                    "lead_days": lead, "n": len(g), "base_rate": base,
                    "brier": bs,
                    "bss": 1 - bs / (base * (1 - base)) if 0 < base < 1 else np.nan,
                })
    return pd.DataFrame(rows)


# ------------------------------------------------------------- figures

def fig_event_totals(totals: pd.DataFrame, st: pd.DataFrame,
                     quality: pd.DataFrame, window: tuple[str, str],
                     outdir: Path) -> None:
    ev = totals
    cities = [c for c in CITY_ORDER if c in set(ev["city"])]
    ev = ev.set_index("city").loc[cities]

    x = np.arange(len(cities))
    width = 0.26
    fig, ax = plt.subplots(figsize=(12, 4.8))
    ax.set_axisbelow(True)  # gridlines behind the bars, not across them
    ax.bar(x - width, ev["station_mm"], width, color=STATION_BAR_COLOR,
           label="Rain gauges (city mean)")
    ax.bar(x, ev["grid_mm"], width, color=GRID_COLOR,
           label="Gridded analysis (IFS HRES 9 km)")
    ax.bar(x + width, ev["ecmwf_ifs025_lead1_mm"], width,
           color=MODEL_COLORS["ecmwf_ifs025"], label="ECMWF IFS, lead 1 (cell)")

    # Each individual gauge behind the city mean, so the reader can see whether
    # the estimate rests on a crowd that agrees or on one instrument.
    used = quality[quality["used"]][["city", "station_id"]]
    ind = (st.merge(used, on=["city", "station_id"])
           .dropna(subset=["precip_station_mm"]))
    ind = ind[in_window(ind["valid_date"], window)]
    ind_tot = ind.groupby(["city", "station_id"])["precip_station_mm"].sum()
    for i, city in enumerate(cities):
        if city in ind_tot.index.get_level_values(0):
            vals = ind_tot.loc[city].to_numpy()
            ax.scatter(np.full(len(vals), i - width), vals, s=18,
                       facecolor="none", edgecolor=INK, linewidth=1.1, zorder=4)
    # The ratio goes above the group's top, bars or gauge circles, whichever
    # reaches higher.
    for i, city in enumerate(cities):
        r = ev.loc[city]
        if np.isfinite(r["grid_over_station"]):
            top = np.nanmax([r["station_mm"], r["grid_mm"],
                             r["ecmwf_ifs025_lead1_mm"]])
            if city in ind_tot.index.get_level_values(0):
                top = max(top, ind_tot.loc[city].max())
            ax.text(i, top + 14, f"{100 * (r['grid_over_station'] - 1):+.0f}%",
                    ha="center", fontsize=8, color=AXIS)

    span = (f"{pd.Timestamp(window[0]).strftime('%d')}–"
            f"{pd.Timestamp(window[1]).strftime('%d %b %Y')}")
    ax.set_xticks(x, [CITY_LABELS[c] for c in cities], rotation=30, ha="right")
    ax.set_ylabel(f"Event total, {span} (mm)")
    ax.set_ylim(0, 1.30 * np.nanmax(
        ev[["station_mm", "grid_mm", "ecmwf_ifs025_lead1_mm"]].to_numpy()))
    ax.legend(loc="upper right", ncol=3, fontsize=9)
    note = ("open circles: the individual gauges behind each city mean   •   "
            "% = gridded analysis relative to the gauges")
    ax.text(0, -0.34, note, transform=ax.transAxes, fontsize=8, color=AXIS)
    n_wet = int((ev["grid_over_station"] > 1).sum())
    ax.set_title("The gridded analysis runs wetter than the gauges in "
                 f"{n_wet} of the {len(cities)} cities", loc="left")
    fig.tight_layout()
    fig.savefig(outdir / "fig6_event_totals_threeway.png", bbox_inches="tight")
    plt.close(fig)


def fig_daily_series(tidy: pd.DataFrame, paired: pd.DataFrame,
                     outdir: Path) -> None:
    cities = [c for c in CITY_ORDER if c in set(paired["city"])]
    ncol = 3
    nrow = int(np.ceil(len(cities) / ncol))
    fig, axes = plt.subplots(nrow, ncol, figsize=(11, 2.5 * nrow),
                             sharex=True, sharey=True)
    fc = tidy[(tidy["model"] == "ecmwf_ifs025") & (tidy["lead_days"] == 1)]
    for ax, city in zip(axes.flat, cities):
        g = paired[paired["city"] == city].sort_values("valid_date")
        f = fc[fc["city"] == city].sort_values("valid_date")
        ax.plot(f["valid_date"], f["precip_fcst_mm"], color=
                MODEL_COLORS["ecmwf_ifs025"], linestyle="--", linewidth=1.5,
                label="ECMWF IFS, lead 1")
        ax.plot(g["valid_date"], g["precip_grid_mm"], color=GRID_COLOR,
                linewidth=2, label="Gridded analysis")
        ax.plot(g["valid_date"], g["precip_gauge_mm"], marker="o",
                markersize=4, linestyle="none", color=STATION_COLOR,
                label="Rain gauges (city mean)")
        n_g = int(g["n_gauges"].max()) if len(g) else 0
        ax.set_title(f"{CITY_LABELS[city]}  ({n_g} gauge{'s' * (n_g != 1)})",
                     fontsize=10, color=INK)
        ax.tick_params(axis="x", rotation=45)
    for ax in axes.flat[len(cities):]:
        ax.set_visible(False)
    for ax in axes[:, 0]:
        ax.set_ylabel("mm/day")
    axes.flat[0].legend(loc="upper left", fontsize=8)
    fig.suptitle("Daily precipitation: gauges, gridded analysis and the "
                 "day-ahead forecast", fontweight="bold")
    fig.tight_layout()
    fig.savefig(outdir / "fig7_station_daily_series.png", bbox_inches="tight")
    plt.close(fig)


# ---------------------------------------------------------------- main

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--capture", default="2026-07-26")
    args = parser.parse_args()

    tidy, st, quality, city_est = load(args.capture)
    metrics_dir = ROOT / "data" / "processed" / args.capture / "metrics"
    metrics_dir.mkdir(parents=True, exist_ok=True)
    fig_dir = ROOT / "figures"

    window = event_window(city_est)
    print(f"event window (majority-wet run around the peak): "
          f"{window[0]} .. {window[1]}")
    totals = event_totals(tidy, city_est, window)
    paired, daily_stats = daily_station_vs_grid(tidy, city_est)
    sens = sensitivity(tidy, paired)

    for name, table in [("gauge_quality_check", quality),
                        ("event_totals_threeway", totals),
                        ("station_vs_grid_daily", daily_stats),
                        ("sensitivity_station_truth", sens)]:
        table.to_csv(metrics_dir / f"{name}.csv", index=False)
    paired.to_csv(metrics_dir / "station_grid_paired_daily.csv", index=False)
    print(f"metrics -> {metrics_dir} (5 CSV files)")

    set_style()
    fig_event_totals(totals, st, quality, window, fig_dir)
    fig_daily_series(tidy, paired, fig_dir)
    print(f"figures -> {fig_dir} (fig6, fig7)")

    print(f"\n{quality['city'].nunique()} cities with gauges, "
          f"{int(quality['used'].sum())} of {len(quality)} gauge-city pairs "
          f"passing QC, {city_est['city'].nunique()} cities with an estimate")
    for reason, n in quality.loc[~quality["used"], "exclusion"].value_counts().items():
        print(f"  excluded, {reason}: {n}")
    pooled = daily_stats[daily_stats["city"] == "(pooled)"]
    for r in pooled.itertuples():
        print(f"  {r.gridded:5s} vs gauges: n={r.n}, bias {r.bias_pc:+.0f}% "
              f"({r.bias_mm:+.2f} mm/day), r={r.pearson_r:.2f} "
              f"(sqrt {r.pearson_r_sqrt:.2f})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
